drop table if exists mpa, users, friends, films, genres, film_genres, likes cascade;

create table if not exists mpa (
	id integer generated by default as identity not null primary key,
	name varchar(255) not null unique
);

create table if not exists users (
	id integer generated by default as identity not null primary key,
	name varchar(255) not null,
	login varchar(255) not null unique,
	email varchar(255) not null,
	birthday date not null
);

create table if not exists friends (
	user_id integer not null references users(id) on delete cascade,
	friend_id integer not null references users(id) on delete cascade
);

create table if not exists films (
	id integer generated by default as identity not null primary key,
	name varchar(255) not null,
	duration integer,
	release_date date,
	description text,
	mpa_id integer not null references mpa(id) on delete restrict
);

create table if not exists genres (
	id integer generated by default as identity not null primary key,
	name varchar(255) not null unique
);

create table if not exists film_genres (
	film_id integer not null references films(id) on delete cascade,
	genre_id integer not null references genres(id) on delete cascade,
	primary key (film_id, genre_id)
);

create table if not exists likes (
	film_id integer not null references films(id) on delete cascade,
	user_id integer not null references users(id) on delete cascade,
	primary key (film_id, user_id)
);